// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBrand = "brands"

// Brand mapped from table <brands>
type Brand struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Nama       string    `gorm:"column:nama;not null" json:"nama"`
	NegaraAsal string    `gorm:"column:negara_asal" json:"negara_asal"`
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Brand's table name
func (*Brand) TableName() string {
	return TableNameBrand
}
