// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceServiceVariant = "device_service_variants"

// DeviceServiceVariant mapped from table <device_service_variants>
type DeviceServiceVariant struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DeviceID  int64     `gorm:"column:device_id;not null" json:"device_id"`
	ServiceID int64     `gorm:"column:service_id;not null" json:"service_id"`
	TipePart  string    `gorm:"column:tipe_part" json:"tipe_part"`
	HargaMin  float64   `gorm:"column:harga_min;not null;default:0.00" json:"harga_min"`
	HargaMax  float64   `gorm:"column:harga_max;not null;default:0.00" json:"harga_max"`
	Catatan   string    `gorm:"column:catatan" json:"catatan"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
	Service *Service `json:"service,omitempty"`
	Device  *Device  `json:"device,omitempty"`
}

// TableName DeviceServiceVariant's table name
func (*DeviceServiceVariant) TableName() string {
	return TableNameDeviceServiceVariant
}
