// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceServiceVariant = "device_service_variants"

type DeviceServiceVariant struct {
	ID         uint      `json:"id" gorm:"primaryKey"`
	DeviceID   uint      `json:"device_id"`
	ServiceID  uint      `json:"service_id"`
	TipePart   *string   `json:"tipe_part,omitempty"`
	HargaMin   float64   `json:"harga_min"`
	HargaMax   float64   `json:"harga_max"`
	Catatan    *string   `json:"catatan,omitempty"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`

	// Relationships
	Device  Device  `json:"device,omitempty" gorm:"foreignKey:DeviceID;references:ID"`
	Service Service `json:"service,omitempty" gorm:"foreignKey:ServiceID;references:ID"`
}


// TableName DeviceServiceVariant's table name
func (*DeviceServiceVariant) TableName() string {
	return TableNameDeviceServiceVariant
}
