// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePriceLog = "price_logs"

// PriceLog mapped from table <price_logs>
type PriceLog struct {
	ID                     int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DeviceServiceVariantID int64     `gorm:"column:device_service_variant_id;not null" json:"device_service_variant_id"`
	UserID                 int64     `gorm:"column:user_id" json:"user_id"`
	OldHargaMin            float64   `gorm:"column:old_harga_min" json:"old_harga_min"`
	OldHargaMax            float64   `gorm:"column:old_harga_max" json:"old_harga_max"`
	NewHargaMin            float64   `gorm:"column:new_harga_min" json:"new_harga_min"`
	NewHargaMax            float64   `gorm:"column:new_harga_max" json:"new_harga_max"`
	TipePart               string    `gorm:"column:tipe_part" json:"tipe_part"`
	ChangedAt              time.Time `gorm:"column:changed_at;not null;default:current_timestamp()" json:"changed_at"`
}

// TableName PriceLog's table name
func (*PriceLog) TableName() string {
	return TableNamePriceLog
}
