// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameService = "services"

// Service mapped from table <services>
type Service struct {
	ID          uint                    `json:"id" gorm:"primaryKey"`
	Nama        string                  `json:"nama"`
	Deskripsi   string                  `json:"deskripsi"`
	CreatedAt   time.Time               `json:"created_at"`
	UpdatedAt   time.Time               `json:"updated_at"`
	Variants    []DeviceServiceVariant  `json:"variants,omitempty" gorm:"foreignKey:ServiceID"`
	Pivot       *DeviceServiceVariant   `json:"pivot,omitempty" gorm:"foreignKey:ServiceID;references:ID"`
}

// TableName Service's table name
func (*Service) TableName() string {
	return TableNameService
}
