// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransaction = "transactions"

// Transaction mapped from table <transactions>
type Transaction struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IDOperator       int64     `gorm:"column:id_operator;not null" json:"id_operator"`
	Status           string    `gorm:"column:status;not null;default:pending" json:"status"`
	MetodePembayaran string    `gorm:"column:metode_pembayaran" json:"metode_pembayaran"`
	JumlahBayar      float64   `gorm:"column:jumlah_bayar" json:"jumlah_bayar"`
	Kembalian        float64   `gorm:"column:kembalian" json:"kembalian"`
	QrisReference    string    `gorm:"column:qris_reference" json:"qris_reference"`
	Total            float64   `gorm:"column:total;not null;default:0.00" json:"total"`
	Details []TransactionDetail `json:"details" gorm:"foreignKey:TransactionID"`
	CreatedAt        time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
	CustomerName     string    `gorm:"column:customer_name" json:"customer_name"`
	CustomerPhone    string    `gorm:"column:customer_phone" json:"customer_phone"`
}

// TableName Transaction's table name
func (*Transaction) TableName() string {
	return TableNameTransaction
}
