// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTransactionDetail = "transaction_details"

// TransactionDetail mapped from table <transaction_details>
type TransactionDetail struct {
	ID                     int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TransactionID          int64     `gorm:"column:transaction_id;not null" json:"transaction_id"`
	DeviceServiceVariantID int64     `gorm:"column:device_service_variant_id;not null" json:"device_service_variant_id"`
	Harga                  float64   `gorm:"column:harga;not null" json:"harga"`
	HargaModal             float64   `gorm:"column:harga_modal" json:"harga_modal"`
	CreatedAt              time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt              time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName TransactionDetail's table name
func (*TransactionDetail) TableName() string {
	return TableNameTransactionDetail
}
